### PR TITLE
Added /comms/byte_order to change stream endianness

### PR DESCRIPTION
**Pull request by ncorgan**

### CODE REVIEW

**Comment by ncorgan** [comment]
Note that I haven't tested the OS X-specific code due to lack of access to a machine.

**Comment by guruofquality** [comment]
> Note that I haven't tested the OS X-specific code due to lack of access to a machine.

Poco has cross platform byteswap https://pocoproject.org/slides/010-Types.pdf `Poco/ByteOrder.h`

**Comment by ncorgan** [comment]
That's what I use in this block, but Poco's implementation doesn't have the faster calls into OSSwapInt32, etc, that UHD's byteswap has; it just defaults to the naive bitshifting. So for the OS X case, I substitute those function in for the Poco ones.

See here: https://github.com/pocoproject/poco/blob/master/Foundation/include/Poco/ByteOrder.h#L151

**Comment by guruofquality** [comment]
Ahh thats too bad for Poco.

**Pull request merged**
